package hotello;


import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VKONCHADA
 */
public class RoomsAndServices extends javax.swing.JFrame {

    /**
     * Creates new form RoomsAndServices
     */
    public RoomsAndServices() {
        initComponents();
        
        //Displaying the image in the Ocean View Label
      {
        ImageIcon myImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Ocean View.jpeg")));
        
        Image image1 = myImage.getImage();
        Image image2 = image1.getScaledInstance(oceanViewLbl.getWidth(),oceanViewLbl.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon a = new ImageIcon(image2);
        
        oceanViewLbl.setIcon(a);
        ocenViewTxtLbl.setText("Ocean View");
      }
        
//Displaying the image in the Double Suite Label
      {
        ImageIcon myImage1 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Double Suite.jpeg")));
        
        Image image3 = myImage1.getImage();
        Image image4 = image3.getScaledInstance(doubleSuiteLbl.getWidth(),doubleSuiteLbl.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon b = new ImageIcon(image4);
        
        doubleSuiteLbl.setIcon(b);
        doubleSuiteTxtLbl.setText("Double Suite");
      }
      
//Displaying the image in the Executive Label      
      {
        ImageIcon myImage2 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Executive.jpeg")));
        
        Image image5 = myImage2.getImage();
        Image image6 = image5.getScaledInstance(ExecutiveLbl.getWidth(),ExecutiveLbl.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon c = new ImageIcon(image6);
        
        ExecutiveLbl.setIcon(c);
        ExecutiveTxtLbl.setText("Executive");
      }
      
//Displaying the image in the Single Label            
      {
        ImageIcon myImage3 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Single.jpeg")));
        
        Image image7 = myImage3.getImage();
        Image image8 = image7.getScaledInstance(SingleLbl.getWidth(),SingleLbl.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon d = new ImageIcon(image8);
        
        SingleLbl.setIcon(d);
        SingleTxtLbl.setText("Single");
      }
      
//Displaying the image in the Spa Label                  
      {
        ImageIcon myImage4 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Spa.png")));
        
        Image image9 = myImage4.getImage();
        Image image10 = image9.getScaledInstance(SpaLbl.getWidth(),SpaLbl.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon e = new ImageIcon(image10);
        
        SpaLbl.setIcon(e);
        SpaTxtLbl.setText("Spa");
      }
      
//Displaying the image in the Restaurant Label        
      {
        ImageIcon myImage5 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Restaurant.jpeg")));
        
        Image image11 = myImage5.getImage();
        Image image12 = image11.getScaledInstance(RestaurantLbl.getWidth(),RestaurantLbl.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon f=new ImageIcon(image12);
        
        RestaurantLbl.setIcon(f);
        RestaurantTxtLbl.setText("Restaurant");
      }
//Displaying the image in the Swimming Pool Label              
      {
        ImageIcon myImage6 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Pool.jpeg")));
        
        Image image13 = myImage6.getImage();
        Image image14 = image13.getScaledInstance(PoolLbl.getWidth(),PoolLbl.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon g = new ImageIcon(image14);
        
        PoolLbl.setIcon(g);
        PoolTxtLbl.setText("Pool");
      }
      
//Displaying the image in the Gym Label              
      {
        ImageIcon myImage7 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Gym.jpeg")));
        
        Image image15 = myImage7.getImage();
        Image image16 = image15.getScaledInstance(GymLbl.getWidth(),GymLbl.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon h = new ImageIcon(image16);
        
        GymLbl.setIcon(h);
        GymTxtLbl.setText("Gym");
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        oceanViewLbl = new javax.swing.JLabel();
        doubleSuiteLbl = new javax.swing.JLabel();
        ExecutiveLbl = new javax.swing.JLabel();
        SingleLbl = new javax.swing.JLabel();
        ocenViewTxtLbl = new javax.swing.JLabel();
        doubleSuiteTxtLbl = new javax.swing.JLabel();
        ExecutiveTxtLbl = new javax.swing.JLabel();
        SingleTxtLbl = new javax.swing.JLabel();
        SpaLbl = new javax.swing.JLabel();
        SpaTxtLbl = new javax.swing.JLabel();
        RestaurantLbl = new javax.swing.JLabel();
        RestaurantTxtLbl = new javax.swing.JLabel();
        PoolLbl = new javax.swing.JLabel();
        PoolTxtLbl = new javax.swing.JLabel();
        GymLbl = new javax.swing.JLabel();
        GymTxtLbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Take A Tour");

        ocenViewTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        doubleSuiteTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        ExecutiveTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        SingleTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        SpaTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        RestaurantTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        PoolTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        GymTxtLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenu1.setText("Back");
        jMenu1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jMenu1ComponentShown(evt);
            }
        });

        jMenuItem2.setText("Main Menu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SpaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(oceanViewLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(doubleSuiteLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RestaurantLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExecutiveLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PoolLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GymLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SingleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(SpaTxtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212)
                        .addComponent(RestaurantTxtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ocenViewTxtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217)
                        .addComponent(doubleSuiteTxtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(220, 220, 220)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ExecutiveTxtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174)
                        .addComponent(SingleTxtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PoolTxtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GymTxtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(oceanViewLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addComponent(doubleSuiteLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(ExecutiveLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(SingleLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ocenViewTxtLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(doubleSuiteTxtLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExecutiveTxtLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SingleTxtLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PoolLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SpaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(RestaurantLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GymLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SpaTxtLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RestaurantTxtLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PoolTxtLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(GymTxtLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jMenu1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ComponentShown

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
 MainMenu frame2 =new MainMenu();
RoomsAndServices.this.setVisible(false);
frame2.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomsAndServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomsAndServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomsAndServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomsAndServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomsAndServices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExecutiveLbl;
    private javax.swing.JLabel ExecutiveTxtLbl;
    private javax.swing.JLabel GymLbl;
    private javax.swing.JLabel GymTxtLbl;
    private javax.swing.JLabel PoolLbl;
    private javax.swing.JLabel PoolTxtLbl;
    private javax.swing.JLabel RestaurantLbl;
    private javax.swing.JLabel RestaurantTxtLbl;
    private javax.swing.JLabel SingleLbl;
    private javax.swing.JLabel SingleTxtLbl;
    private javax.swing.JLabel SpaLbl;
    private javax.swing.JLabel SpaTxtLbl;
    private javax.swing.JLabel doubleSuiteLbl;
    private javax.swing.JLabel doubleSuiteTxtLbl;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel oceanViewLbl;
    private javax.swing.JLabel ocenViewTxtLbl;
    // End of variables declaration//GEN-END:variables
}
